export const CONST_EVENTS = {
  PAGE_VIEW: 'page_view',
  FOCUS_GAIN: 'focus_gain',
  TAB_CLOSE: 'tab_close',
  ACTIVE: 'active',
  IS_TRACKING_ENABLED: 'IS_TRACKING_ENABLED',
  PAUSE_TRACKING: 'PAUSE_TRACKING',
  RESUME_TRACKING: 'RESUME_TRACKING',
  SET_BADGE_ENABLED: 'SET_BADGE_ENABLED',
  GET_TODAY_TIME: 'GET_TODAY_TIME',
  GET_STATS: 'GET_STATS',
  EXPORT_DATA: 'EXPORT_DATA',
  CLEAR_DATA: 'CLEAR_DATA',
  VISIBILITY_CHANGE: 'VISIBILITY_CHANGE',
  SCROLL_DEPTH: 'scroll_depth',
  CLICK: 'click',
  KEYDOWN: 'keydown',
  FORM_INTERACTION: 'form_interaction',
  SPA_ROUTE_CHANGE: 'spa_route_change',

  visibilitychange: 'visibilitychange',
  beforeunload: 'beforeunload',
  focus: 'focus',
  blur: 'blur',
  pagehide: 'pagehide',
  pageshow: 'pageshow',

  COMPLETE: 'complete',
} as const

export const indicatorColors = [
  '#ff6b6b',
  '#4ecdc4',
  '#45b7d1',
  '#96ceb4',
  '#feca57',
  '#ff9ff3',
  '#54a0ff',
  '#5f27cd',
] as const